{{ if eq .Cluster.ConfigItems "kube_janitor_enabled" "true" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kube-janitor
  namespace: kube-system
  labels:
    application: kubernetes
    component: kube-janitor
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-janitor
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: janitor
      maxAllowed:
        memory: 4Gi
{{ end }}
