# for github.com
approvals:
  # needed to keep the compliance checks happy
  groups:
    zalando:
      minimum: 2
      from:
        orgs:
          - zalando
    maintainers:
      minimum: 2
      from:
        users:
          - linki
          - mikkeloscar
          - szuecs
          - katyanna
          - AlexanderYastrebov
          - zaklawrencea
          - myaser
          - demonCoder95
          - RomanZavodskikh
          - MustafaSaber

# mandatory pull request labels
pull-request:
  labels:
    additional: true
    oneOf:
      - architectural
      - major
      - minor
      - bugfix
      - documentation
      - dependencies

X-Zalando-Team: "teapot"
