apiVersion: zalando.org/v1
kind: RouteGroup
metadata:
  name: deployment-service-status-service
  namespace: kube-system
  labels:
    application: deployment-service
    component: status-service
spec:
  hosts:
    - deployment-status-svc-{{ .Cluster.Alias }}.{{ .Values.hosted_zone }}
    - deployment-status-service.ingress.cluster.local
  backends:
    - name: deployment-service-status-service
      type: service
      serviceName: deployment-service-status-service
      servicePort: 80
    - name: shunt
      type: shunt
  defaultBackends:
    - backendName: deployment-service-status-service
  routes:
    - pathSubtree: /
    - path: /healthz
      filters:
        - status(403)
      backends:
        - backendName: shunt
