{{ if eq .Cluster.ConfigItems.role_sync_controller_enabled "true" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: role-sync-controller
  namespace: kube-system
  labels:
    application: kubernetes
    component: role-sync-controller
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      labels:
        application: kubernetes
        component: role-sync-controller
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            application: kubernetes
            component: role-sync-controller
        spec:
          serviceAccountName: role-sync-controller
          restartPolicy: OnFailure
          containers:
          - name: role-sync-controller
            image: container-registry.zalando.net/teapot/role-sync-controller:main-2
            args:
              - --subject-group=PowerUser
              - --subject-group=Manual
              - --subject-group=Emergency
              - --subject-group=okta:common/engineer
              - --subject-serviceaccount=default/cdp
              - --subject-user=zalando-iam:zalando:service:k8sapi-local_deployment-service-executor
              {{- if eq .Cluster.Environment "test"}}
              - --subject-group=CollaboratorPowerUser
              {{- end}}
              {{- if eq .Cluster.Provider "zalando-eks"}}
              - --subject-serviceaccount=kube-system/deployment-service-controller
              {{- end}}
{{ end }}
