{{ if eq .Cluster.ConfigItems.role_sync_controller_enabled "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-sync-controller
  labels:
    application: kubernetes
    component: role-sync-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: poweruser
subjects:
- kind: ServiceAccount
  name: role-sync-controller
  namespace: kube-system
{{ end }}
