{{ if .Cluster.ConfigItems.role_sync_controller_enabled "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: role-sync-controller
  namespace: kube-system
  labels:
    application: kubernetes
    component: role-sync-controller
{{ end }}
